### PR TITLE
fix(ui): convert inline event handlers to addEventListener for innerHTML guard compatibility (#3372)

### LINKED ISSUE #3372: [BUG]: Team selector dropdown items not clickable — onclick stripped by innerHTML sanitizer
### 🐞 Bug Summary
Clicking a team in the header team selector dropdown does nothing — no navigation, no console errors, no network request. The team list loads and highlights on hover, but selecting a team does not apply team scope (`?team_id=X`).

---

### 🧩 Affected Component
- [x] `mcpgateway` - UI (admin panel)

---

### 🔁 Steps to Reproduce

1. Log in to the admin UI
2. Click the team selector dropdown in the header
3. Wait for team list to load
4. Click any team in the dropdown

**Expected:** Page navigates to `?team_id=<id>#<current-tab>`
**Actual:** Nothing happens

---

### Root Cause
`installInnerHtmlGuard()` in `admin.js` (PR #3129) globally overrides `Element.prototype.innerHTML` to strip all `on*` event handler attributes for XSS protection. When `loadTeams()` injects team selector items via `container.innerHTML = html`, the `onclick="selectTeamFromSelector(this)"` attributes are removed. The buttons render but have no click handler.

---

### 📓 Logs / Error Output
Paste any relevant stack traces or logs here.
⚠️ **Do not paste secrets, credentials, or tokens.**

---

### 🧠 Environment Info
| Key | Value |
|-----|-------|
| Introduced in | PR #3129 (medium hardening batch) |
| Affects | All commits after `a2c8d749f` |
| Component | `mcpgateway/static/admin.js`, `mcpgateway/templates/teams_selector_items.html` |

---

### 🧩 Additional Context (optional)
Add any configuration details, flags, or related issues.

### PR DESCRIPTION
**Pull request by madhav165**
# 🐛 Bug-fix PR
Closes #3372

---

## 📌 Summary
`installInnerHtmlGuard()` (PR #3129) strips all inline `on*` event attributes from HTML set via `innerHTML` for XSS protection. This breaks every dynamically loaded UI element that relied on inline `onclick`/`onchange` handlers.

Most visible symptom: team selector dropdown items in the admin header are unclickable.

## 🔁 Reproduction Steps
1. Log in to admin UI
2. Click the team selector dropdown in the header
3. Click any team in the list
4. Nothing happens — no navigation, no console errors, no network request

## 🐞 Root Cause
`installInnerHtmlGuard()` in `admin.js` (PR #3129) overrides `Element.prototype.innerHTML` to strip all `on*` attributes for XSS protection. When `loadTeams()` sets `container.innerHTML = html`, the `onclick="selectTeamFromSelector(this)"` on each `.team-selector-item` button is removed.

## 💡 Fix Description
Converted all affected inline `onclick`/`onchange` attributes to `data-action` attributes, then attached event listeners via `addEventListener` after each innerHTML assignment. Uses event delegation where appropriate (tables, lists).

### Affected locations (all fixed):
1. **Team selector dropdown** — event delegation on `#team-selector-items`
2. **Team selector search error retry** — addEventListener after innerHTML
3. **Team selector loadTeams error retry** (admin.html) — addEventListener after innerHTML
4. **Metrics error/retry buttons** — data-action + addEventListener
5. **Metrics empty state retry** — data-action + addEventListener
6. **Tag filter clear button** — data-action + addEventListener
7. **Auth header toggle/remove buttons** — data-action + addEventListener
8. **Import file chooser reset** — data-action + addEventListener
9. **Token list error retry** — data-action + addEventListener
10. **Token usage stats modal close** — data-action + addEventListener
11. **Bulk import selection controls** — data-action + addEventListener (select all/none/custom, reset, preview, import, checkbox onchange)
12. **Tool table action buttons** — event delegation on `#toolBody` (enrich, generate tests, validate, view, edit)
13. **Global search results** — addEventListener after innerHTML
14. **Public team join buttons** — addEventListener after innerHTML
15. **Chat server selection** — addEventListener after innerHTML
16. **Log viewer rows + correlation trace** — event delegation on tbody
17. **Security events correlation trace** — addEventListener after innerHTML
18. **Audit trail correlation trace** — addEventListener after innerHTML

## 🧪 Verification

| Check                                 | Command              | Status |
|---------------------------------------|----------------------|--------|
| Playwright regression test            | `pytest ...::TestTeamSelectorDropdown` | ✅ |
| URL contains `?team_id=` after click  | manual + Playwright  | ✅ |
| Existing team/org tests               | `pytest test_organization.py` | ✅ |
| No remaining inline onclick in innerHTML strings | Verified via grep | ✅ |

## ✅ Checklist
- [x] Root cause identified and verified with Playwright
- [x] All innerHTML+onclick paths converted to data-action + addEventListener
- [x] Regression test added
- [x] No secrets/credentials committed

### CODE REVIEW

**Review by suciu-daniel — APPROVED** [review]
Code seems ok, I do not see any glaring issues in it. I will take the branch on my local machine and test it manually as well, in order to ensure the buttons do their job

File: mcpgateway/static/admin.js [hunk 1]
```diff
@@ -12113,6 +12125,40 @@ async function loadTools() {
...
 document.addEventListener("DOMContentLoaded", loadTools);
 
+// Event delegation for tool table action buttons (inline onclick stripped by innerHTML sanitizer).
+// Bind to #tool-ops-main-content-wrapper (exists in admin.html at DOMContentLoaded) rather than
+// #toolBody (injected later via HTMX partial) so the listener survives HTMX content swaps.
+document.addEventListener("DOMContentLoaded", function () {
+    const wrapper =
+        document.getElementById("tool-ops-main-content-wrapper") ||
+        document.getElementById("toolBody");
+    if (wrapper) {
```
Comment (VladMRusu1) [inline mcpgateway/static/admin.js:12135]: Maybe you could add here an early return in order to not have the whole code wrapped into a if

File: mcpgateway/static/admin.js [hunk 2]
```diff
@@ -12113,6 +12125,40 @@ async function loadTools() {
...
+                case "generate-tool-tests":
+                    generateToolTestCases(toolId);
+                    break;
+                case "validate-tool":
+                    validateTool(toolId);
+                    break;
+                case "view-tool":
+                    viewTool(toolId);
+                    break;
+                case "edit-tool":
```
Comment (VladMRusu1) [inline mcpgateway/static/admin.js:12154]: do we want a default case if a wrong btn.dataset.action was generated?

File: mcpgateway/static/admin.js [hunk 3]
```diff
@@ -23713,6 +23819,15 @@ function displayPublicTeams(teams) {
             ${teamsHtml}
         </div>
     `;
+
+    // Attach click listeners (inline onclick stripped by innerHTML sanitizer)
+    container
```
Comment (VladMRusu1) [inline mcpgateway/static/admin.js:23824]: are we sure that we will have always a container available? maybe an extra check if container exists

File: mcpgateway/static/admin.js [hunk 4]
```diff
@@ -24267,24 +24382,49 @@ function displayImportPreview(preview) {
...
+                <button data-action="import-selected"
                         class="px-4 py-2 text-sm font-medium text-white bg-green-600 border border-transparent rounded-md hover:bg-green-700">
                     ✅ Import Selected Items
                 </button>
             </div>
         </div>
     `;
 
+    // Attach event listeners (inline onclick/onchange is stripped by innerHTML sanitizer)
+    previewContainer
```
Comment (VladMRusu1) [inline mcpgateway/static/admin.js:24404]: I think here is possible to have an actionMap with using of event delegation

```
const actionMap = {
    "select-all": () => selectAllItems(),
    "select-none": () => selectNoneItems(),
    "select-custom": () => selectOnlyCustom(),
    "reset-selection": () => resetImportSelection(),
    "preview-selected": () => handleSelectiveImport(true),
    "import-selected": () => handleSelectiveImport(false),
};

previewContainer.addEventListener("click", (e) => {
    const actionEl = e.target.closest("[data-action]");
    if (!actionEl) return;

    const action = actionEl.dataset.action;
    actionMap[action]?.();
});
```

and the change event will be handle separately 

```
previewContainer.addEventListener("change", (e) => {
    if (e.target.matches('[data-action="update-count"]')) {
        updateSelectionCount();
    }
});
```

**Comment by crivetimihai** [comment]
Thanks @madhav165. Thorough work — converting all 18 inline handler sites to `data-action` + `addEventListener` is the correct approach to maintain XSS protection from the innerHTML guard. The event delegation pattern on tables/lists is well-applied. Excellent PR description and root cause analysis.

File: mcpgateway/static/admin.js (hunk 2 above)
Comment (gcgoncalves) [reply mcpgateway/static/admin.js:12154]: I'm not sure that would be the best approach, any guesses might be wrong. The only acceptable default, IMHO, would be a void function to act as a "disabler".
