### PR TITLE
fix[bug]: handle non-JSON responses and query params in REST tools (#3855, #3857) 

### LINKED ISSUE #3855: [BUG][UI]: Admin UI Tool "Invoke" button non-functional — invokeTool() undefined
The Admin UI Tool "Test" and "Invoke" action buttons are completely non-functional. When users click these buttons and try to test a tool, they receive a JSON-RPC error `"Invalid method"` with code `-32000`. The root cause is missing
  JavaScript function definitions (`invokeTool()` and `runToolTest()`) that are referenced by onclick handlers but never defined in the template.                                                                                                   
  
  ---                                                                                                                                                                                                                                               
                                                            
  ### 🧩 Affected Component                                                                                                                                                                                                                         
  Select the area of the project impacted:
                                                                                                                                                                                                                                                    
  - [ ] `mcpgateway` - API                                  
  - [x] `mcpgateway` - UI (admin panel)
  - [ ] `mcpgateway.wrapper` - stdio wrapper                                                                                                                                                                                                        
  - [ ] Federation or Transports
  - [ ] CLI, Makefiles, or shell scripts                                                                                                                                                                                                            
  - [ ] Container setup (Docker/Podman/Compose)             
  - [ ] Other (explain below)                                                                                                                                                                                                                       
                                                            
  ---                                                                                                                                                                                                                                               
                                                            
  ### 🔁 Steps to Reproduce                                                                                                                                                                                                                         
  
  1. Start ContextForge server: `make dev` or `make serve`                                                                                                                                                                                          
  2. Navigate to Admin UI at `http://localhost:4444/admin`  
  3. Go to the **Tools** section                                                                                                                                                                                                                    
  4. Create a REST tool:
     ```json                                                                                                                                                                                                                                        
     {                                                      
       "name": "test-tool",                                                                                                                                                                                                                         
       "url": "https://webhook.site/0f547174-a653-4ec1-bc97-278db9f51c5f",
       "integration_type": "REST",                                                                                                                                                                                                                  
       "request_type": "POST",
       "description": "Test webhook tool",                                                                                                                                                                                                          
       "input_schema": {                                    
         "type": "object",                                                                                                                                                                                                                          
         "properties": {                                    
           "message": {                                                                                                                                                                                                                             
             "type": "string"                               
           }                                                                                                                                                                                                                                        
         },
         "required": ["message"]                                                                                                                                                                                                                    
       }                                                    
     }
  5. Click the "Test" button (or "Invoke" button) for the tool
  6. In the modal, fill in the test parameters:                                                                                                                                                                                                     
    - message: "hello test from rak"           
    - (Optional) Add passthrough headers                                                                                                                                                                                                            
  7. Click "Run Tool" button                                
  8. Observe the error response in the UI                                                                                                                                                                                                           
                                                            
  ---                                                                                                                                                                                                                                               
  🤔 Expected Behavior                                      
                                                                                                                                                                                                                                                    
  What should happen:
  1. Tool test modal opens with input fields based on input_schema                                                                                                                                                                                  
  2. User fills in required parameters                                                                                                                                                                                                              
  3. Clicking "Run Tool" sends a proper JSON-RPC request:
  {                                                                                                                                                                                                                                                 
    "jsonrpc": "2.0",                                                                                                                                                                                                                               
    "method": "tools/call",
    "params": {                                                                                                                                                                                                                                     
      "name": "test-tool",                                                                                                                                                                                                                          
      "arguments": {      
        "message": "hello test from rak"                                                                                                                                                                                                            
      }                                                     
    },                                                                                                                                                                                                                                              
    "id": 1774432249817
  }                                                                                                                                                                                                                                                 
  4. Request goes to /mcp endpoint with proper headers      
  5. Tool executes and returns results (success or failure)
  6. Results display in the modal                                                                                                                                                                                                                   
  
  ---                                                                                                                                                                                                                                               
  📋 Actual Behavior                                        
                                                                                                                                                                                                                                                    
  Error displayed in UI modal:                              
  {      
    "jsonrpc": "2.0",
    "error": {                                                                                                                                                                                                                                      
      "code": -32000,
      "message": "Invalid method",                                                                                                                                                                                                                  
      "data": {                                                                                                                                                                                                                                     
        "message": "hello test from rak"
      }                                                                                                                                                                                                                                             
    },                                                      
    "id": 1774432249817                                                                                                                                                                                                                             
  }
                                                                                                                                                                                                                                                    
  Screenshot showing the error:                             
  screenshot_showing_error.png
                                                                                                                                                                                                                                                    
  The test modal displays:
  - ✅ Input fields render correctly based on schema                                                                                                                                                                                                
  - ✅ User can enter values                                                                                                                                                                                                                        
  - ✅ "Run Tool" button is clickable
  - ❌ Clicking "Run Tool" produces "Invalid method" error                                                                                                                                                                                          
  - ❌ Tool is never actually invoked                       
                                                                                                                                                                                                                                                    
  ---                                                                                                                                                                                                                                               
  🔍 Root Cause Analysis                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    
  Missing JavaScript Functions:                             

  Two critical functions are referenced but never defined in mcpgateway/templates/admin.html:                                                                                                                                                       
  
  1. invokeTool(toolName) - Line 12129                                                                                                                                                                                                              
  // CALLED HERE (button creation):                         
  buttons += `<button onclick="invokeTool('${item.name}')" ...>Invoke</button>`;                                                                                                                                                                    
                                                                                
  // FUNCTION DEFINITION: ❌ MISSING                                                                                                                                                                                                                
                                    
  2. runToolTest() - Line 8529                                                                                                                                                                                                                      
  // CALLED HERE (Run Tool button):                                                                                                                                                                                                                 
  <button onclick="runToolTest()">Run Tool</button>
                                                                                                                                                                                                                                                    
  // FUNCTION DEFINITION: ❌ MISSING                        
                                                                                                                                                                                                                                                    
  Verification:                                             
  # Confirm functions are called but not defined                                                                                                                                                                                                    
  grep -c "invokeTool" mcpgateway/templates/admin.html      
  # Output: 1 (only the onclick call, no function definition)
                                                                                                                                                                                                                                                    
  grep -c "runToolTest" mcpgateway/templates/admin.html                                                                                                                                                                                             
  # Output: 1 (only the onclick call, no function definition)                                                                                                                                                                                       
                                                                                                                                                                                                                                                    
  What likely happens:                                                                                                                                                                                                                              
  1. User clicks "Test" or "Invoke" → Browser tries to call undefined function
  2. JavaScript error may be caught or fail silently                                                                                                                                                                                                
  3. Some fallback code sends a malformed request OR        
  4. Browser calls the function name as a method directly → backend rejects as "Invalid method"                                                                                                                                                     
                                                                                                                                                                                                                                                    
  ---
  📓 Logs / Error Output                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    
  Browser Console (expected):
  Uncaught ReferenceError: invokeTool is not defined                                                                                                                                                                                                
      at HTMLButtonElement.onclick                          
  or                                                                                                                                                                                                                                                
  Uncaught ReferenceError: runToolTest is not defined
      at HTMLButtonElement.onclick                                                                                                                                                                                                                  
                                                            
  Server logs:                                                                                                                                                                                                                                      
  ERROR - Method not found: <tool-name>
                                                                                                                                                                                                                                                    
  JSON-RPC Response (from UI):                              
  {                                                                                                                                                                                                                                                 
    "jsonrpc": "2.0",                                       
    "error": {                                                                                                                                                                                                                                      
      "code": -32000,
      "message": "Invalid method",                                                                                                                                                                                                                  
      "data": {                                             
        "message": "hello test from rak"                                                                                                                                                                                                            
      }                                 
    },                                                                                                                                                                                                                                              
    "id": 1774432249817                                                                                                                                                                                                                             
  }
                                                                                                                                                                                                                                                    
  API endpoint invoked (likely incorrect):                  
  - Expected: POST /mcp with method: "tools/call"
  - Actual: POST /mcp with method: "test-tool" (tool name as method) OR malformed request                                                                                                                                                           
  
  ---                                                                                                                                                                                                                                               
  ✅ Workaround: CLI/API Testing Works                      
                                                                                                                                                                                                                                                    
  The tool configuration itself is correct. Users can test tools successfully via CLI/API:
                                                                                                                                                                                                                                                    
  # Generate token                                          
  source ~/.venv/mcpgateway/bin/activate                                                                                                                                                                                                            
  TOKEN=$(python -m mcpgateway.utils.create_jwt_token \
    --username admin@example.com \                                                                                                                                                                                                                  
    --admin \                                               
    --exp 10080 \                                                                                                                                                                                                                                   
    --secret my-test-key 2>/dev/null)                       
                                                                                                                                                                                                                                                    
  # Test the tool via API (THIS WORKS)                                                                                                                                                                                                              
  curl -X POST "http://localhost:4444/mcp" \
    -H "Authorization: Bearer $TOKEN" \                                                                                                                                                                                                             
    -H "Content-Type: application/json" \                                                                                                                                                                                                           
    -H "Accept: application/json" \
    -d '{                                                                                                                                                                                                                                           
      "jsonrpc": "2.0",                                                                                                                                                                                                                             
      "method": "tools/call",
      "params": {                                                                                                                                                                                                                                   
        "name": "test-tool",                                                                                                                                                                                                                        
        "arguments": {
          "message": "hello test from rak"                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                           
      },
      "id": 1                                                                                                                                                                                                                                       
    }'                                                      

  Response (via API):                                                                                                                                                                                                                               
  {
    "jsonrpc": "2.0",                                                                                                                                                                                                                               
    "id": 1,                                                
    "result": {                                                                                                                                                                                                                                     
      "content": [{
        "type": "text",                                                                                                                                                                                                                             
        "text": "Tool invocation failed: Expecting value: line 1 column 1 (char 0)"                                                                                                                                                                 
      }],                                                                          
      "isError": true                                                                                                                                                                                                                               
    }                                                       
  }                                                                                                                                                                                                                                                 
                                                            
  ⚠️  Important Note About This Response:
  The "Tool invocation failed: Expecting value" error is misleading - it does NOT mean the tool is broken! Here's what actually happened:                                                                                                           
                                                                                                                                                                                                                                                    
  1. ✅ ContextForge sent the HTTP POST request successfully to webhook.site                                                                                                                                                                        
  2. ✅ webhook.site received the request (verified in webhook.site dashboard logs)                                                                                                                                                                 
  3. ✅ Your tool configuration is correct                                                                                                                                                                                                          
  4. ✅ HTTP POST is reaching webhook.site                                                                                                                                                                                                          
  5. ❌ webhook.site returns HTML (not JSON) in its response                                                                                                                                                                                        
  6. ❌ ContextForge tries to parse HTML as JSON → "Expecting value: line 1 column 1 (char 0)"                                                                                                                                                      
                                                                                                                                                                                                                                                    
  Proof that the tool actually works:                                                                                                                                                                                                               
  - Open webhook.site dashboard: https://webhook.site/0f547174-a653-4ec1-bc97-278db9f51c5f                                                                                                                                                          
  - You will see POST requests arriving with the message payload {"message": "hello test from rak"}                                                                                                                                                 
  - The HTTP POST is successfully reaching the endpoint                                            
                                                                                                                                                                                                                                                    
  Comparison with JSON-returning endpoint:                                                                                                                                                                                                          
  # Test with httpbin.org (returns JSON)                                                                                                                                                                                                            
  curl -X POST "http://localhost:4444/mcp" \                                                                                                                                                                                                        
    -H "Authorization: Bearer $TOKEN" \                                                                                                                                                                                                             
    -H "Content-Type: application/json" \                                                                                                                                                                                                           
    -H "Accept: application/json" \                                                                                                                                                                                                                 
    -d '{                                                                                                                                                                                                                                           
      "jsonrpc": "2.0",                                     
      "method": "tools/call",                                                                                                                                                                                                                       
      "params": {                                                                                                                                                                                                                                   
        "name": "test-echo-api",
        "arguments": {                                                                                                                                                                                                                              
          "message": "Testing",                             
          "value": 42                                                                                                                                                                                                                               
        }                                                   
      },                                                                                                                                                                                                                                            
      "id": 2                                               
    }'                                                                                                                                                                                                                                              
                                                            
  Response:
  {                                                                                                                                                                                                                                                 
    "jsonrpc": "2.0",
    "id": 2,                                                                                                                                                                                                                                        
    "result": {                                             
      "content": [{
        "type": "text",                                                                                                                                                                                                                             
        "text": "{\"args\": {}, \"data\": \"{...}\", ...}"
      }],                                                                                                                                                                                                                                           
      "isError": false                                                                                                                                                                                                                              
    }
  }                                                                                                                                                                                                                                                 
                                                            
  Conclusion:                                                                                                                                                                                                                                       
  - ✅ Tool invocation via API works correctly              
  - ✅ REST tools are functioning properly                                                                                                                                                                                                          
  - ❌ Admin UI Test/Invoke buttons are broken (primary issue)
  - ⚠️  Response parsing errors are cosmetic (secondary issue - webhook.site returns HTML)                                                                                                                                                           
                                                                                                                                                                                                                                                    
                                                                                                                                                          
                                                                                                                                                                                                                                                    
                                                                              
  
<img width="1346" height="1460" alt="Image" src="https://github.com/user-attachments/assets/5c407c48-28e2-4c37-b91a-32756e64331a" />

<img width="804" height="664" alt="Image" src="https://github.com/user-attachments/assets/3b26f54a-b96a-4658-a1ab-45b5e8646407" />

### PR DESCRIPTION
**Pull request by rakdutta**
Closes #3855 and #3857                                                                                                                                                                                                                            
  
  This PR enhances REST tool robustness by improving error handling, query parameter processing, and input validation. It also streamlines the admin UI tool testing workflow.                                                                      
                             
  Backend Improvements

  Non-JSON Response Handling (#3855)                                                                                                                                                                                                                
  - New _handle_json_parse_error() helper function for graceful fallback when JSON parsing fails
  - Handles multiple exception types: json.JSONDecodeError, orjson.JSONDecodeError, UnicodeDecodeError, AttributeError                                                                                                                              
  - Supports REST APIs returning HTML error pages, plain text, XML, or responses with encoding issues                 
  - Returns raw text as {"response_text": <truncated>} instead of crashing                                                                                                                                                                          
                                                                                                                                                                                                                                                    
  Response Truncation (Security Enhancement)                                                                                                                                                                                                        
  - New configurable setting: REST_RESPONSE_TEXT_MAX_LENGTH (default: 5000 chars, range: 1000-100000)                                                                                                                                               
  - Truncates non-JSON response text to prevent exposing excessive sensitive data in error responses                                                                                                                                                
  - Applies to both success and error responses                                                                                                                                                                                                     
  - Logs warning when truncation occurs with original and truncated lengths                                                                                                                                                                         
                                                                                                                                                                                                                                                    
  Query Parameter Handling (#3857)                                                                                                                                                                                                                  
  - GET requests: URL query params merged with input arguments (URL params take precedence on conflicts)                                                                                                                                            
  - POST/PUT/PATCH/DELETE: Query params preserved in URL to support signed URLs (Azure SAS, AWS presigned URLs, webhook signatures)                                                                                                                 
  - Added conflict warning when URL query params override input arguments for better debugging                                     
                                                                                                                                                                                                                                                    
  jq Filter Validation                                                                                                                                                                                                                              
  - Added validation to detect simple email addresses mistakenly used as jq filters (e.g., user@example.com)                                                                                                                                        
  - Uses regex pattern ^[^.\[\]|]+@[^.\[\]|]+\.[^.\[\]|]+$ to catch basic email patterns without false positives                                                                                                                                    
  - Logs warning and treats invalid filters as empty (returns unfiltered data)                                  
                                                                                                                                                                                                                                                    
  Frontend Enhancements                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                    
  Admin UI Tool Testing Workflow                                                                                                                                                                                                                    
  - New invokeTool(toolName) function called by "Invoke" buttons in Tools table
  - Fetches tool details via API (fetchToolDetails) and populates modal dynamically                                                                                                                                                                 
  - Dynamic form generation from tool input schema (createFormInput, generateToolFormFields)
  - Refactored runToolTest() and runToolValidation() to use consistent tools/call method structure:                                                                                                                                                 
  {                                                                                                                                                                                                                                                 
    method: "tools/call",                                                                                                                                                                                                                           
    params: { name: toolName, arguments: {...} }                                                                                                                                                                                                    
  }                                                                                                                                                                                                                                                 
  - Enhanced error logging for better debugging                                                                                                                                                                                                     
                                                                                                                                                                                                                                                    
  Test Coverage                                                                                                                                                                                                                                     
                             
  Comprehensive test suite added:                                                                                                                                                                                                                   
  - TestJqFilterEmailValidation: Email address detection and valid filter preservation
  - TestRestToolQueryParamHandling: GET/POST/PUT/PATCH/DELETE param handling, conflict warnings                                                                                                                                                     
  - TestRestToolNonJsonResponses: HTML, plain text, XML, encoding errors, empty responses      
  - Truncation tests: large responses, small responses, custom config values

### CODE REVIEW

**Review by crivetimihai — APPROVED** [review]
Nice work on this one — the core idea of handling non-JSON REST responses and fixing query param handling for signed URLs is solid and well-motivated.

## What I changed during rebase

The branch had significant merge conflicts since `admin.js` was split into ES modules (#3137) after this PR was opened. I rebased onto current `main`, squashed the 22 commits into one clean commit, and made the following adjustments:

### JS changes ported to modular structure
- All JS changes now target `mcpgateway/admin_ui/tools.js` and `admin_ui/admin.js` instead of the old monolithic `admin.js`
- Used `fetchWithTimeout` (already imported) instead of raw `fetch` + `getCookie` for consistency with the existing `testTool()` function
- Replaced `innerHTML` assignments with safe DOM methods (`removeChild`, `createElement`, `textContent`) to avoid XSS vectors

### Fixed unreachable 4xx/5xx error handling (critical)
The original code placed the non-JSON error response handling *after* `response.raise_for_status()`, which throws `httpx.HTTPStatusError` for 4xx/5xx — making the error branch unreachable for the exact cases #3855 describes.

Fixed by catching `HTTPStatusError` and handling the error response in the except block:
- Parses body with the same JSON/non-JSON fallback
- Includes HTTP status code in the error message (`"HTTP 500: <truncated html>"`)
- Sets `structured_content={"status_code": N}` so the retry plugin can distinguish retriable (503) from non-retriable (404) errors — matching the existing pattern at line 5040

The original `elif status not in [200, 201, 202, 206]` branch is retained for non-standard 2xx codes (203, 205, 207).

### Test fix
Updated the HTML error response test to actually raise `httpx.HTTPStatusError` from `raise_for_status()` instead of mocking it to no-op — the original test passed but didn't exercise the real production code path.

## Verification
- 290/290 tests in `test_tool_service.py` pass (18 new)
- 323/323 tests in `test_tool_service_coverage.py` pass
- Linters clean (black, isort, eslint)

File: mcpgateway/admin_ui/tools.js [hunk 1]
```diff
@@ -3501,3 +3509,182 @@ export const cleanupToolTestModal = function () {
...
+// ===================================================================
+// TOOL INVOCATION (opens test modal by tool name)
+// ===================================================================
+
+/**
+ * Fetch tool details from the API by name.
+ * @param {string} toolName - The name of the tool to fetch
+ * @returns {Promise<Object>} The tool object
+ */
+async function fetchToolDetails(toolName) {
```
Comment (gcgoncalves) [inline mcpgateway/admin_ui/tools.js]: It might be good to export this and the other new functions added, so that we can unit test them directly.

File: tests/unit/js/tools.test.js
Comment (gcgoncalves) [inline tests/unit/js/tools.test.js:1]: Consider adding unit tests for fetchToolDetails, createFormInput, generateToolFormFields and invokeTool.
